### ISSUE TITLE
Bug in batched CPHASE - with suggested fix

### ISSUE THREAD

**Issue by vincentelfving** [pasqal-io/PyQ#27]
bug: batched CPHASE is initialized as a real-valued matrix, causing the casting of complex value to one of the entries to reals, losing information and making the operation unusable (it throws the error `RuntimeError: expected scalar type Float but found ComplexDouble` when any CPHASE is used in a circuit). The simple fix is to just initialise the matrix as a torch.cdouble.

This means [this line ](https://github.com/pasqal-io/PyQ/blob/4fec6ddc134ad7ae6a8ded0e5b3e978e00620afb/pyqtorch/core/batched_operation.py#L387) should be changed from
```
mat = torch.eye(4).repeat((batch_size,1,1))
```
to
```
mat = torch.eye(4, torch.cdouble).repeat((batch_size,1,1))
``` 

I think not all of the operations/gates in PR #18 have unit tests yet, that is why this went unnoticed. So I suggest let's use this Issue also for adding those tests for the existing operations. Tagging potentially relevant people @dominikandreasseitz @Roland-djee @madagra

**Comment by dominikandreasseitz** [comment]
Hi Vincent! Thanks for catching that one. You are right, we are lacking unit tests. We will fix it!

**Comment by dominikandreasseitz** [comment]
@vincentelfving i added the fix and a test file which checks that the gates actually work.
