### ISSUE TITLE
`HamEvo` modules are mutating the input state

### ISSUE THREAD

**Issue by nmheim** [pasqal-io/PyQ#35]
e.g. [here](https://github.com/pasqal-io/PyQ/blob/main/tests/test_operations_hamevo.py#L41) this means we have to deepcopy states to make tests pass. this should be fixed for example [here](https://github.com/pasqal-io/PyQ/blob/main/pyqtorch/core/operation.py#L547).

**Comment by dominikandreasseitz** [comment]
https://github.com/pasqal-io/PyQ/pull/38 fixes this
