### ISSUE TITLE
Unify the three hamiltonian evolution classes into one `HamiltonianEvolution`

### ISSUE THREAD

**Issue by madagra** [pasqal-io/PyQ#53]
**Update for clarity: This issue is about the Module API.**
There are currently 3 different ways to implement the Hamiltonian evolution in PyQ. We should allow the user to select the type of operation when initializing the gate operation in the quantum circuit constructor instead of doing it through three different classes.

Unify the three classes in `pyqtorch.modules.hamevo` into one which accepts an Enum that determines which method is used.

```python
class HamiltonianEvolution(Module):
    def __init__(
        self,
        qubits: Any,
        n_qubits: int,
        n_steps: int = 100,
        # the type should be an enum that also accepts string inputs
        type: HamEvoType=HamEvoType.RK4
    ):
```

**Comment by zain2864** [comment]
Hi, can I take on this issue for Unitary Hack?

**Comment by dominikandreasseitz** [comment]
Hi @zain2864 ! welcome to pyq and thanks for wanting to contribute! yes, go ahead! let me know if you have any questions/troubles setting things up
